class InfoBoxConst():
    title = 'タイトル'
    genre= 'ジャンル'
    director = '監督'
    scenario = 'シナリオ'
    character_design = 'キャラクターデザイン'
    production_company = 'アニメーション制作'
    broadcasts = '放送局'
    publisher = '出版社'
    original_work = '原作'
    label = 'レーベル'
    music = '音楽'
    number_of_story = '話数'
